markehammons/slinc

.gitignore
build.sc
core/docs/_docs/reference/usage.md
core/src/fr/hammons/slinc/LibraryI.scala
core/src/fr/hammons/slinc/Slinc.scala
core/src/fr/hammons/slinc/container/Capabilities.scala
core/src/fr/hammons/slinc/container/ContextProof.scala
core/src/fr/hammons/slinc/container/ContextSet.scala
core/src/fr/hammons/slinc/types/HostDependentTypes.scala
core/src/fr/hammons/slinc/types/TypesI.scala
core/src/fr/hammons/slinc/types/x64/Linux.scala
core/src/fr/hammons/slinc/types/x64/Mac.scala
core/src/fr/hammons/slinc/types/x64/Windows.scala
core/test/src/fr/hammons/slinc/BindingsSpec.scala

Add support for host specific bindings

---

.github/workflows/ci.yml

Add runtime tests to CI workflow

---

core/src/fr/hammons/slinc/DataLayout.scala
core/src/fr/hammons/slinc/LayoutI.scala
core/src/fr/hammons/slinc/Receive.scala
core/src/fr/hammons/slinc/Send.scala
core/src/fr/hammons/slinc/Struct.scala
core/test/resources/native/test.c
core/test/src/fr/hammons/slinc/BindingSpec.scala
core/test/src/fr/hammons/slinc/TransferSpec.scala
j17/src/fr/hammons/slinc/LayoutI17.scala
j17/src/fr/hammons/slinc/Mem17.scala
j19/src/fr/hammons/slinc/LayoutI19.scala
j19/src/fr/hammons/slinc/Mem19.scala

How to access pointer field in static C Struct

---

.github/workflows/benchmarks.yml
.github/workflows/ci.yml

Create performance reports

---

build.sc

chore: Upgrade to Scala 3.2.2

---

core/src/fr/hammons/slinc/MethodHandleFacade.java

chore: Add MethodHandleFacade calls to arity 22

---

.scalafmt.conf
core/benchmarks/test/src/fr/hammons/slinc/BindingsBenchmarkShape.scala
core/src/fr/hammons/slinc/CFunctionBindingGenerator.scala
core/src/fr/hammons/slinc/Lib.scala
core/src/fr/hammons/slinc/LibBacking.scala
core/src/fr/hammons/slinc/Slinc.scala
core/src/fr/hammons/slinc/TypeDescriptor.scala
core/src/fr/hammons/slinc/modules/LibModule.scala
core/src/fr/hammons/slinc/modules/LinkageModule.scala
core/test/src/fr/hammons/slinc/LibSpec.scala
j17/src/fr/hammons/slinc/Slinc17.scala
j17/src/fr/hammons/slinc/modules/LibModule17.scala
j17/src/fr/hammons/slinc/modules/LinkageModule17.scala
j17/src/fr/hammons/slinc/modules/ReadWriteModule17.scala
j17/test/src/fr/hammons/slinc/LibSpec17.scala
j19/src/fr/hammons/slinc/Slinc19.scala
j19/src/fr/hammons/slinc/modules/LibModule19.scala
j19/src/fr/hammons/slinc/modules/LinkageModule19.scala
j19/src/fr/hammons/slinc/modules/ReadWriteModule19.scala
j19/test/src/fr/hammons/slinc/LibSpec19.scala

Make non-variadic, non-generic standard C library bindings platform independent

---

core/src/fr/hammons/slinc/CFunctionBindingGenerator.scala
core/src/fr/hammons/slinc/CFunctionDescriptor.scala
core/src/fr/hammons/slinc/FunctionDescriptor.scala
core/src/fr/hammons/slinc/Lib.scala
core/src/fr/hammons/slinc/MethodHandler.scala
core/src/fr/hammons/slinc/Ptr.scala
core/src/fr/hammons/slinc/TypeDescriptor.scala
core/src/fr/hammons/slinc/modules/LibModule.scala
core/src/fr/hammons/slinc/modules/LinkageModule.scala
core/src/fr/hammons/slinc/modules/ReadWriteModule.scala
core/test/src/fr/hammons/slinc/LibSpec.scala
j17/src/fr/hammons/slinc/modules/LibModule17.scala
j17/src/fr/hammons/slinc/modules/LinkageModule17.scala
j17/src/fr/hammons/slinc/modules/ReadWriteModule17.scala
j19/src/fr/hammons/slinc/modules/LibModule19.scala
j19/src/fr/hammons/slinc/modules/LinkageModule19.scala
j19/src/fr/hammons/slinc/modules/ReadWriteModule19.scala

feat:Make C library bindings support variadic downcalls

---

core/benchmarks/test/src/fr/hammons/slinc/BindingsBenchmarkShape.scala
core/src/fr/hammons/slinc/Alias.scala
core/src/fr/hammons/slinc/DescriptorOf.scala
core/src/fr/hammons/slinc/Lib.scala
core/src/fr/hammons/slinc/Struct.scala
core/src/fr/hammons/slinc/TypeDescriptor.scala
core/src/fr/hammons/slinc/modules/ReadWriteModule.scala
core/src/fr/hammons/slinc/types/CLong.scala
core/src/fr/hammons/slinc/types/IntegralAlias.scala
core/src/fr/hammons/slinc/types/SizeT.scala
core/src/fr/hammons/slinc/types/TimeT.scala
core/test/src/fr/hammons/slinc/LibSpec.scala
j17/src/fr/hammons/slinc/modules/DescriptorModule17.scala
j17/src/fr/hammons/slinc/modules/ReadWriteModule17.scala
j17/src/fr/hammons/slinc/modules/TransitionModule17.scala
j19/src/fr/hammons/slinc/modules/DescriptorModule19.scala
j19/src/fr/hammons/slinc/modules/ReadWriteModule19.scala
j19/src/fr/hammons/slinc/modules/TransitionModule19.scala

feat: Add AliasDescriptor

---

core/src/fr/hammons/slinc/types/Basic.scala

chore: Create C primitive type aliases

---

core/benchmarks/test/src/fr/hammons/slinc/BindingsBenchmarkShape.scala
core/src/fr/hammons/slinc/FSet.scala
core/src/fr/hammons/slinc/FSetBacking.scala
core/src/fr/hammons/slinc/FunctionBindingGenerator.scala
core/src/fr/hammons/slinc/FunctionContext.scala
core/src/fr/hammons/slinc/Slinc.scala
core/src/fr/hammons/slinc/modules/FSetModule.scala
core/test/src/fr/hammons/slinc/BindingSpec.scala
core/test/src/fr/hammons/slinc/FSetRuntimeSpec.scala
core/test/src/fr/hammons/slinc/FSetSpec.scala
core/test/src/fr/hammons/slinc/StdlibSpec.scala
j17/src/fr/hammons/slinc/Slinc17.scala
j17/src/fr/hammons/slinc/modules/FSetModule17.scala
j17/test/src/fr/hammons/slinc/FSetRuntimeSpec17.scala
j17/test/src/fr/hammons/slinc/LibSpec17.scala
j19/src/fr/hammons/slinc/Slinc19.scala
j19/src/fr/hammons/slinc/modules/FSetModule19.scala
j19/test/src/fr/hammons/slinc/FSetRuntimeSpec19.scala
j19/test/src/fr/hammons/slinc/LibSpec19.scala

refactor: Rename Lib to Module

---

core/src/fr/hammons/slinc/FSet.scala
core/src/fr/hammons/slinc/annotations/NeedsResource.scala
core/src/fr/hammons/slinc/fset/Dependency.scala
core/src/fr/hammons/slinc/modules/FSetModule.scala
core/src/fr/hammons/slinc/modules/LinkageModule.scala
core/src/fr/hammons/slinc/modules/LinkageTools.scala
core/test/src/fr/hammons/slinc/FSetSpec.scala
core/test/src/fr/hammons/slinc/modules/LinkageToolsSpec.scala
j17/src/fr/hammons/slinc/modules/FSetModule17.scala
j17/src/fr/hammons/slinc/modules/LinkageModule17.scala
j19/src/fr/hammons/slinc/modules/FSetModule19.scala
j19/src/fr/hammons/slinc/modules/LinkageModule19.scala

feat: Platform and runtime bindings should be able to bind to shared libraries in resources.

---

core/src/fr/hammons/slinc/FSet.scala
core/src/fr/hammons/slinc/annotations/DependencyAnnotation.scala
core/src/fr/hammons/slinc/annotations/NeedsResource.scala
core/src/fr/hammons/slinc/fset/Dependency.scala
core/src/fr/hammons/slinc/modules/CacheFile.scala
core/src/fr/hammons/slinc/modules/LinkageTools.scala
core/test/src/fr/hammons/slinc/FSetRuntimeSpec.scala
core/test/src/fr/hammons/slinc/FSetSpec.scala
core/test/src/fr/hammons/slinc/modules/LinkageToolsSpec.scala
j17/src/fr/hammons/slinc/modules/FSetModule17.scala
j19/src/fr/hammons/slinc/modules/FSetModule19.scala

refactor: C library bindings should be able to be made against c files in resources

---

build.sc
core/src/fr/hammons/slinc/FSet.scala
core/src/fr/hammons/slinc/annotations/NeedsFile.scala
core/src/fr/hammons/slinc/fset/Dependency.scala
core/src/fr/hammons/slinc/modules/LinkageTools.scala
core/test/src/fr/hammons/slinc/FSetRuntimeSpec.scala
core/test/src/fr/hammons/slinc/FSetSpec.scala
libs/test-code.c

FSet dependencies to relative paths
FSet dependencies to absolute paths
Fixes #94, #95

feat: File dependencies supported by FSet

---

core/src/fr/hammons/slinc/TypeDescriptor.scala
core/test/resources/native/test.c
j17/src/fr/hammons/slinc/modules/DescriptorModule17.scala
j19/src/fr/hammons/slinc/modules/DescriptorModule19.scala

feat: Add TypeDescriptor for va_list

---

.github/workflows/ci.yml
build.sc
core/src/fr/hammons/slinc/modules/LinkageTools.scala
core/test/src/fr/hammons/slinc/BindingSpec.scala
j17/test/src/fr/hammons/slinc/TransferSpec.scala

ci: Fix broken CI

---

core/src/fr/hammons/slinc/TypeDescriptor.scala
core/test/resources/native/test.c
core/test/src/fr/hammons/slinc/BindingSpec.scala
core/test/src/fr/hammons/slinc/TransferSpec.scala
j17/src/fr/hammons/slinc/VarArgs17.scala
j17/src/fr/hammons/slinc/modules/DescriptorModule17.scala
j19/src/fr/hammons/slinc/Allocator19.scala
j19/src/fr/hammons/slinc/VarArgs19.scala

feat: Add transition for va_list

---

core/benchmarks/test/src/fr/hammons/slinc/BindingsBenchmarkShape.scala

- use state instead of fixed value
- consume `Unit` by Blackhole to prevent compiler from eliminating false dead code.

bench: comply with known practices

---

core/src/fr/hammons/slinc/Mem.scala
core/src/fr/hammons/slinc/Ptr.scala
core/test/resources/native/test.c
core/test/src/fr/hammons/slinc/BindingSpec.scala
core/test/src/fr/hammons/slinc/TransferSpec.scala

feat: Add ability to compare pointers

---

core/src/fr/hammons/slinc/Scope.scala
core/test/src/fr/hammons/slinc/TransferSpec.scala
j17/src/fr/hammons/slinc/Scope17.scala
j17/test/src/fr/hammons/slinc/TransferSpec.scala
j19/src/fr/hammons/slinc/Scope19.scala
j19/test/src/fr/hammons/slinc/Transfer19.scala
runtime/test/src/fr/hammons/slinc/Transfers.scala

feat: Add shared scope method to slinc
